"""night products

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-07 17:34:09.897847
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('night_id', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('thumbnail', sa.Boolean(), nullable=False),
    sa.Column('has_full', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_thumb', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('full_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_product_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('device_id', 'night_id', 'name', name=op.f('uq_product_device_id_night_id_name'))
    )
    op.create_index(op.f('ix_product_created_at'), 'product', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_created_at'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
