"""events

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-08 15:15:15.008046
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('event_id', sa.String(length=48), nullable=False),
    sa.Column('night_id', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('has_image', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_full', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_thumb', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_event_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event')),
    sa.UniqueConstraint('device_id', 'event_id', name=op.f('uq_event_device_id_event_id'))
    )
    op.create_index(op.f('ix_event_created_at'), 'event', ['created_at'], unique=False)
    op.create_index(op.f('ix_event_night_id'), 'event', ['night_id'], unique=False)
    op.create_index(op.f('ix_event_start'), 'event', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_start'), table_name='event')
    op.drop_index(op.f('ix_event_night_id'), table_name='event')
    op.drop_index(op.f('ix_event_created_at'), table_name='event')
    op.drop_table('event')
    # ### end Alembic commands ###
