"""devices and pairing

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 14:44:39.793554
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_nonce',
    sa.Column('nonce_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('nonce_hash', name=op.f('pk_device_nonce'))
    )
    op.create_index(op.f('ix_device_nonce_expires_at'), 'device_nonce', ['expires_at'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('public_key', sa.LargeBinary(length=32), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('auth_generation', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_frame', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latest_image_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_account.id'], name=op.f('fk_device_owner_id_user_account'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device')),
    sa.UniqueConstraint('public_key', name=op.f('uq_device_public_key'))
    )
    op.create_index(op.f('ix_device_owner_id'), 'device', ['owner_id'], unique=False)
    op.create_table('device_token',
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('auth_generation', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_device_token_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash', name=op.f('pk_device_token'))
    )
    op.create_index(op.f('ix_device_token_device_id'), 'device_token', ['device_id'], unique=False)
    op.create_table('pairing_code',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by'], ['user_account.id'], name=op.f('fk_pairing_code_claimed_by_user_account'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_pairing_code_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pairing_code'))
    )
    op.create_index(op.f('ix_pairing_code_device_id'), 'pairing_code', ['device_id'], unique=False)
    op.create_index('uq_pairing_code_open_code', 'pairing_code', ['code'], unique=True, postgresql_where=sa.text('claimed_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_pairing_code_open_code', table_name='pairing_code', postgresql_where=sa.text('claimed_at IS NULL'))
    op.drop_index(op.f('ix_pairing_code_device_id'), table_name='pairing_code')
    op.drop_table('pairing_code')
    op.drop_index(op.f('ix_device_token_device_id'), table_name='device_token')
    op.drop_table('device_token')
    op.drop_index(op.f('ix_device_owner_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_device_nonce_expires_at'), table_name='device_nonce')
    op.drop_table('device_nonce')
    # ### end Alembic commands ###
