"""event labels

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-08 16:21:24.152463
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('label', sa.String(length=16), nullable=True))
    op.add_column('event', sa.Column('labelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'labelled_at')
    op.drop_column('event', 'label')
    # ### end Alembic commands ###
