"""frame archive

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-07 17:14:31.643493
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frame',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('night_id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('exposure_us', sa.BigInteger(), nullable=False),
    sa.Column('gain', sa.Float(), nullable=False),
    sa.Column('mean', sa.Float(), nullable=False),
    sa.Column('sun_elevation', sa.Float(), nullable=False),
    sa.Column('has_full', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('has_thumb', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_frame_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_frame')),
    sa.UniqueConstraint('device_id', 'night_id', 'name', name=op.f('uq_frame_device_id_night_id_name'))
    )
    op.create_index(op.f('ix_frame_created_at'), 'frame', ['created_at'], unique=False)
    op.add_column('device', sa.Column('latest_thumb_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'latest_thumb_at')
    op.drop_index(op.f('ix_frame_created_at'), table_name='frame')
    op.drop_table('frame')
    # ### end Alembic commands ###
