"""push notifications

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-08 17:21:32.322844
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=4096), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], name=op.f('fk_push_token_user_id_user_account'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_token')),
    sa.UniqueConstraint('token', name=op.f('uq_push_token_token'))
    )
    op.create_index(op.f('ix_push_token_user_id'), 'push_token', ['user_id'], unique=False)
    op.add_column('device', sa.Column('offline_notified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_account', sa.Column('notify_events', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_account', sa.Column('notify_offline', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'notify_offline')
    op.drop_column('user_account', 'notify_events')
    op.drop_column('device', 'offline_notified_at')
    op.drop_index(op.f('ix_push_token_user_id'), table_name='push_token')
    op.drop_table('push_token')
    # ### end Alembic commands ###
