"""public sky page

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-08 14:55:02.465147
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('public_slug', sa.String(length=32), nullable=True))
    op.create_unique_constraint(op.f('uq_device_public_slug'), 'device', ['public_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_device_public_slug'), 'device', type_='unique')
    op.drop_column('device', 'public_slug')
    # ### end Alembic commands ###
