"""sky samples

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-08 18:25:19.485340
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0012'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sky_sample',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=26), nullable=False),
    sa.Column('night_id', sa.String(length=8), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('sqm_mag', sa.Float(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_sky_sample_device_id_device'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sky_sample')),
    sa.UniqueConstraint('device_id', 'at', name=op.f('uq_sky_sample_device_id_at'))
    )
    op.create_index(op.f('ix_sky_sample_created_at'), 'sky_sample', ['created_at'], unique=False)
    op.create_index(op.f('ix_sky_sample_night_id'), 'sky_sample', ['night_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sky_sample_night_id'), table_name='sky_sample')
    op.drop_index(op.f('ix_sky_sample_created_at'), table_name='sky_sample')
    op.drop_table('sky_sample')
    # ### end Alembic commands ###
